name = "socket-server"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "aeeb6270a84f4da2e7366198360b9700"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm test && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
  {name = "CHATROOM", class_name = "ChatRoom"}
]
